version: "3.8"
services:
    myProject-image:
        build:
            context: .
            dockerfile: Dockerfile
        image: myproject-image
        container_name: myproject_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "8083:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network

    myProject-db:
        image: mariadb:latest
        container_name: mariadb_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: myproject
            MYSQL_ROOT_PASSWORD: votran1508
            MYSQL_USER: votran
            MYSQL_PASSWORD: votran1508
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
        driver: local
